name: whampy

channels:
    - conda-forge

dependencies:
    - python=>3.6
    - sphinx-astropy
    - astropy
    - matplotlib
    - numpy
    - pip
    - pip:
        - basemap
#       - dependency_from_pip
