name: whampy

channels:
    - conda-forge

dependencies:
    - python=>3.6
    - sphinx-astropy
    - astropy
    - numpy
    - basemap
    - matplotlib
    - pyproj
    - pyshp
    - proj4
    # - pip
    # - pip:
        # - basemap
#       - dependency_from_pip
