name: whampy

channels:
    - conda-forge

dependencies:
    - python=>3.6
    - sphinx-astropy
    - astropy
    - numpy
    - matplotlib
    - cartopy
    - regions
    - pandas
    - seaborn
    # - pyproj
    # - pyshp
    # - proj4
    # - pip
    - pip:
        - spectral_cube
	- healpy
        - dustmaps
        - extinction
    #     - git+https://github.com/matplotlib/basemap.git
#       - dependency_from_pip
