name: whampy

channels:
    - conda-forge

dependencies:
    - python=>3.6
    - sphinx-astropy
    - astropy
    - numpy
    - matplotlib
    - cartopy
    # - pyproj
    # - pyshp
    # - proj4
    # - pip
    # - pip:
    #     - git+https://github.com/matplotlib/basemap.git
#       - dependency_from_pip
