[build-system]
requires = [
  "setuptools>=62.1",
  "setuptools_scm[toml]>=8.0.0",
  "wheel",]
build-backend = "setuptools.build_meta"

[project]
name = "whampy"
description = "Python Package to Interact with, Visualize, and Analyze the Wisconsin H-Alpha Mapper - Sky Survey"
requires-python = ">=3.9"
readme = { file = "README.rst", content-type = "text/x-rst" }
license = { file = "LICENSE.rst" }
dependencies = ["astropy","numpy","matplotlib","scipy","seaborn"]
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-doctestplus",
    "pytest-cov",
]
docs = [
    "sphinx",
    "sphinx-automodapi",
]

[tool.setuptools]
zip-safe = false
include-package-data = true

[tool.setuptools.packages.find]
include = ["whampy*"]
exclude = ["paper", "astropy_helpers"]

[tool.setuptools_scm]
version_file = "whampy/version.py"

[tool.pytest.ini_options]
testpaths = [
  "whampy",
  "docs",
]
doctest_plus = "enabled"
text_file_format = "rst"
addopts = "--doctest-rst"
norecursedirs = ["whampy[\\/]_dev"]

[tool.coverage.run]
omit = [
 "whampy/__init*",
 "whampy/conftest.py",
 "whampy/*setup_package*",
 "whampy/tests/*",
 "whampy/*/tests/*",
 "whampy/extern/*",
 "whampy/version*",
 "*/whampy/__init*",
 "*/whampy/conftest.py",
 "*/whampy/*setup_package*",
 "*/whampy/tests/*",
 "*/whampy/*/tests/*",
 "*/whampy/extern/*",
 "*/whampy/version*",
]

[tool.coverage.report]
exclude_lines = [
  # Have to re-enable the standard pragma
  "pragma: no cover",
  # Don't complain about packages we have installed
  "except ImportError",
  # Don't complain if tests don't hit assertions
  "raise AssertionError",
  "raise NotImplementedError",
  # Don't complain about script hooks
  "def main(.*):",
  # Ignore branches that don't pertain to this version of Python
  "pragma: py{ignore_python_version}",
  # Don't complain about IPython completion helper
  "def _ipython_key_completions_",
  # typing.TYPE_CHECKING is False at runtime
  "if TYPE_CHECKING:",
  # Ignore typing overloads
  "@overload",
]